### ISSUE TITLE
New table for kitchen

### ISSUE THREAD

**Issue by fairlight1337** [code-iai/longterm_fetch_and_place#3]
We need the table to set (the piece of furniture) in the simulated model, as well as a corrected version of the one currently residing in bullet (and rviz).

There is still an old pancake table in the current model loaded into rviz and bullet which we don't need. Additionally, we decided on the side-tables in the lab to be the table to set (meeting from last week, see Trello). This table needs to be in the model, properly positioned in the URDF, and semantically defined in the OWL (collision environment as well as supporting surface).

@bbrieber, @gaya-, is this something you can look into?

Also, Michael asked for walls in the simulation; like the ones we have in the lab. It would be great if those could be part of the URDF; no necessity to have them defined in the OWL, though (unless we want them to be part of the MoveIt! collision scene).

**Comment by bbrieber** [comment]
I already talked to minerva and she has created a model of this kind of table?
I can add it to a gazebo map, and the semantic map. The walls in the simulation work currently only in gazebo versions higher than 2.X because they have been created with the building editor. 
I can export manually create another SDF for them if this is a problem. (There is a worldfile for this)

I guess the walls should also be part of the owl so they can be visualized in openEASE.

**Comment by fairlight1337** [comment]
Okay, I see, thanks. Just add it to the map and we'll see where it fits, that would be great.

About the walls, maybe we can just add simpler versions of it to the scene; we'd have to ask Michael what he thinks though. But that would be a quick, painless fix :).

**Comment by bbrieber** [comment]
I added the table https://github.com/code-iai/iai_maps/pull/20 and the walls https://github.com/code-iai/iai_maps/pull/21 to the map.

There is no semantic representation for both of them at the moment. But I will do that as soon as the actual real position is fixed.

**Comment by fairlight1337** [comment]
This was done.
